#!/bin/bash
echo "             THE INTERNATIONAL PHONETIC ALPHABET (revised to 2015)             "
echo "                                                                               "
echo "-------------------------------------------------------------------------------"
echo "CONSONANTS (PULMONIC)                                              (c) 2015 IPA"
echo "-------------------------------------------------------------------------------"
echo "           bil   lab   den   alv   pos   ret   pal   vel   uvu   pha   glo     "
echo "Plosive  | p b |     |       t d       | ʈ ɖ | c ɟ | k ɡ | q ɢ |   ░ | ʔ ░ |   "
echo "Nasal    |   m |   ɱ |         n       |   ɳ |   ɲ |   ŋ |   ɴ | ░░░ | ░░░ |   "
echo "Trill    |   ʙ |     |         r       |     |     | ░░░ |   ʀ |     | ░░░ |   "
echo "Tap/flap |     |   ⱱ |         ɾ       |   ɽ |     | ░░░ |     |     | ░░░ |   "
echo "Fricat.  | ɸ β | f v | θ ð | s z | ʃ ʒ | ʂ ʐ | ç ʝ | x ɣ | χ ʁ | ħ ʕ | h ɦ |   "
echo "Lateral  | ░░░ | ░░░ |       ɬ ɮ       |     |     |     |     | ░░░ | ░░░ |   "
echo "Approx.  |     |     |   ʋ     ɹ     ɻ |   j |   ɰ |     |     |     | ░░░ |   "
echo "Lat. app | ░░░ | ░░░ |         l       |   ɭ |   ʎ |   ʟ |     | ░░░ | ░░░ |   "
echo "···············································································"
echo "Symbols to the right in a cell are voiced, to the left are voiceless. Shaded   "
echo "areas denote articulations judged impossible.                                  "
echo "                                                                               "
echo "-----------------------------------------       -------------------------------"
echo "CONSONANTS (NON-PULMONIC)                       VOWELS                         "
echo "-----------------------------------------       -------------------------------"
echo "    CLICKS      VOI. IMPL.    EJECTIVES                Front  Centr     Back   "
echo "| ʘ Bilabial  | ɓ Bilabial | ’  Examples        Close  i•y --- ɨ•ʉ --- ɯ •u    "
echo "| ǀ Dental    | ɗ Dent/Alv | p’ Bilabial                 \ ɪ ʏ   \  ʊ    |     "
echo "| ǃ Pos. alv  | ʄ Palatal  | t’ Dent/Alv.       Clmid    e•ø --- ɘ•ɵ -- ɤ•o    "
echo "| ǂ Pal. alv  | ɠ Velar    | k’ Velar                      \      ə      |     "
echo "| ǁ Alv. lat  | ʛ Uvular   | s’ Alv. Fric.      Opmid      ɛ•œ -- ɜ•ɞ - ʌ•ɔ    "
echo "                                                             æ      ɐ    |     "
echo "-----------------------------------------       Open          a•ɶ ----- ɑ•ɒ    "
echo "OTHER SYMBOLS                                                                  "
echo "------------------------------------------      Where symbols appear in pairs, "
echo " ʍ -Voi.lbvel.fri.  ɕ ʑ Alv.pal.fric            the one to the right represents"
echo " w Voi.labvel.app.  ɺ Voi.alv.lat.flap          a rounded vowel.               "
echo " ɥ Voi.labpal.app.  ɧ Simultaneous h & ʃ                                       "
echo " ʜ -Voi.epigl.fri.  Affricates and double      ------------------------------- "
echo " ʢ Voi.epigl.fric.  articulations with a       SUPRASEGMENTALS                 "
echo " ʡ Epiglotal plos.  tie bar. t͜s kp͡            --------------------------------"
echo "                                                ˈ Prim stress | ˌ Secnd stress "
echo "DIACRITICS                                      ː Long        | ˑ Half-Long    "
echo "------------------------------------------     ⠀̆  Extra-short                  "
echo "Some diacritics may be placed above a           | Minor       | ‖ Major       "
echo "symbol with a descender, e.g. ŋ̊                 . Syllable break               "
echo "-----------------------------------------       ‿ Linking                     "
echo "|⠀̥  -voile n̥  |⠀̤  breath b̤  |⠀̪  dental t̪                                       "
echo "|⠀̬  +voicd s̬  |⠀̰  creaky b̰  |⠀̺  apical t̺      ---------------------------------"
echo "|⠀ʰ asprtd tʰ |⠀̼  linglb t̼  |⠀̻  lamin  t̻      TONES & WORD ACCENTS             "
echo "|⠀̹  +round ɔ̹  |⠀ʷ labial tʷ |⠀̃  nasal  ẽ      ---------------------------------"
echo "|⠀̹  -round ɔ̨  |⠀ʲ palat  tʲ |⠀ⁿ nasrel dⁿ       LEVEL        CONTOUR           "
echo "|⠀̟  advcd  u̟  |⠀ˠ velar  tˠ |⠀ˡ latrel dˡ     e̋ ~ ˥ +Hi    ě ~ ˩˥ Rising       "
echo "|⠀̠  retrtd e̠  |⠀ˤ phary  tˤ |⠀̚ -audre d̚       é ~ ˦ High   ê ~ ˥˩ Falling    "    
echo "|⠀̈  cntrld ë  | ⠀̴ vel/ph l̴                    ê ~ ˧ Mid    e᷄ ~ ˧˥ High-Rising"    
echo "|⠀̽  mid-ce e̽  |⠀̝  raisd  e̝ ɻ̝ (voi.alv.fr)     ē ~ ˨ Low    e᷅ ~ ˩˧  Low-Rising  "  
echo "|⠀̩  syllbc n̩  |⠀̞  lower  e̞ β̞ (voi.lab.ap)     ȅ ~ ˩ +low   e᷈ ~ ˧˦˨ Rising-Fall."  
echo "|⠀̯  -sylbc e̽  |⠀̘  ATR    e̘                    ꜜ Downstep   ↗ Global rise       "   
echo "|⠀. rhocty ə˞ |⠀̙  RTR    e̙                    ꜛ Upstep     ↘ Global Fall       "  
echo "                                                                               "
echo "Updated in Sept, 2024                                                    by ABC"
