#!/bin/bash
echo "     THE INTERNATIONAL PHONETIC ALPHABET "
echo "                                (revised to 2015)"
echo "-------------------------------------------------"
echo "CONSONANTS (PULMONIC)                (c) 2015 IPa"
echo "-------------------------------------------------"
echo "     bil lab den alv pos ret pal vel uvu pha glo"
echo "Plo |p b|   |    t d    |ʈ ɖ|c ɟ|k ɡ|q ɢ|  ░|ʔ ░|"
echo "Nas |  m| ɱ |      n    |  ɳ|  ɲ|  ŋ|  ɴ|░░░|░░░|" # ɱ is weird, it needs an space afterwards otherwise it looks aweful!
echo "Tri |  ʙ|   |      r    |   |   |░░░|  ʀ|   |░░░|"
echo "Tap |   |  ⱱ|      ɾ    |  ɽ|   |░░░|   |   |░░░|"
echo "Fri |ɸ β|f v|θ ð|s z|ʃ ʒ|ʂ ʐ|ç ʝ|x ɣ|χ ʁ|ħ ʕ|h ɦ|"
echo "Lat |░░░|░░░|    ɬ ɮ    |   |   |   |   |░░░|░░░|"
echo "App |   |   |  ʋ   ɹ   ɻ|  j|  ɰ|   |   |   |░░░|"
echo "Lap |░░░|░░░|      l    |  ɭ|  ʎ|  ʟ|   |░░░|░░░|"
echo "·················································"
echo "Symbols to the right in a cell are voiced, "
echo "to the left are voiceless. Shaded areas denote "
echo "articulations judged impossible."
echo ""
echo "-------------------------------------------------"
echo "VOWELS                       "
echo "-------------------------------------------------"
echo "       Front  Centr     Back "
echo "Close  i•y --- ɨ•ʉ --- ɯ •u  "  # ɯ is weird, it needs an space afterwards otherwise it looks aweful!
echo "         \ ɪ ʏ   \   ʊ   |   "
echo "Clmid    e•ø --- ɘ•ɵ -- ɤ•o  "
echo "           \      ə      |   "
echo "Opmid      ɛ•œ -- ɜ•ɞ - ʌ•ɔ  "
echo "             æ      ɐ    |   "
echo "Open          a•ɶ ----- ɑ•ɒ  "
echo "·····························"
echo "Where symbos appear in pairs, the one to the"
echo "right represents a rounded vowel."
echo ""
echo "-------------------------------------------------"
echo "CONSONANTS (NON-PULMONIC)"
echo "-------------------------------------------------"
echo "    Clicks      Voi. Impl.     Ejectives     "
echo "| ʘ Bilabial  | ɓ Bilabial |  ’ Examples:  | "
echo "| ǀ Dental    | ɗ Dent/Alv | p’ Bilabial   | "
echo "| ǃ Pos. alv  | ʄ Palatal  | t’ Dent/Alv.  | "
echo "| ǂ Pal. alv  | ɠ Velar    | k’ Velar      | "
echo "| ǁ Alv. lat  | ʛ Uvular   | s’ Alv. Fric. | "
echo "·············································"



    
